"""initial schema

Revision ID: 09280d0a4e9e
Revises: 
Create Date: 2026-07-08 07:17:52.256793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09280d0a4e9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('short_label', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('financial_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('running_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=150), nullable=True),
    sa.Column('is_active_flag', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_number', sa.String(length=50), nullable=False),
    sa.Column('grn_number', sa.String(length=50), nullable=True),
    sa.Column('boe_number', sa.String(length=50), nullable=True),
    sa.Column('supplier_invoice_ref', sa.String(length=100), nullable=True),
    sa.Column('bill_of_supply_number', sa.String(length=100), nullable=True),
    sa.Column('supplier_name', sa.String(length=200), nullable=True),
    sa.Column('cha_name', sa.String(length=200), nullable=False),
    sa.Column('shipping_line', sa.String(length=200), nullable=True),
    sa.Column('container_number', sa.String(length=100), nullable=True),
    sa.Column('port', sa.String(length=100), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.Column('clearance_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipments_boe_number'), ['boe_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_file_number'), ['file_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_shipments_grn_number'), ['grn_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_supplier_invoice_ref'), ['supplier_invoice_ref'], unique=False)

    op.create_table('approval_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=False),
    sa.Column('financial_year_id', sa.Integer(), nullable=True),
    sa.Column('running_number', sa.Integer(), nullable=False),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('subject_text', sa.Text(), nullable=True),
    sa.Column('paragraph_1', sa.Text(), nullable=True),
    sa.Column('paragraph_2', sa.Text(), nullable=True),
    sa.Column('paragraph_3', sa.Text(), nullable=True),
    sa.Column('paragraph_4', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('recoverable_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('company_borne_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('payable_to_cha', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_notes_document_number'), ['document_number'], unique=True)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('invoice_type', sa.String(length=100), nullable=False),
    sa.Column('vendor_name', sa.String(length=200), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('invoice_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gst', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('bill_of_supply', sa.String(length=100), nullable=True),
    sa.Column('srn', sa.String(length=100), nullable=True),
    sa.Column('cha_ref', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('classification', sa.String(length=30), nullable=True),
    sa.Column('company_borne_reason', sa.String(length=50), nullable=True),
    sa.Column('recover_from', sa.String(length=50), nullable=True),
    sa.Column('recover_from_party', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_note_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('action_by_id', sa.Integer(), nullable=True),
    sa.Column('action_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['action_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['approval_note_id'], ['approval_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments')
    op.drop_table('approval_history')
    op.drop_table('invoices')
    with op.batch_alter_table('approval_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_notes_document_number'))

    op.drop_table('approval_notes')
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipments_supplier_invoice_ref'))
        batch_op.drop_index(batch_op.f('ix_shipments_grn_number'))
        batch_op.drop_index(batch_op.f('ix_shipments_file_number'))
        batch_op.drop_index(batch_op.f('ix_shipments_boe_number'))

    op.drop_table('shipments')
    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('financial_years')
    op.drop_table('charge_types')
    # ### end Alembic commands ###
